# stage 0
FROM node:12.14.1-alpine AS build-env

# install dependencies
COPY ./ /app
WORKDIR /app
RUN npm install --registry=https://registry.npm.taobao.org

# build
ENV NODE_ENV=production
RUN npm run build

# stage 1
FROM nginx:alpine AS production-dev

# copy product
RUN mkdir /app
COPY --from=0 /app/dist /app

# setup nginx
RUN rm /etc/nginx/conf.d/default.conf
COPY ./server.conf /etc/nginx/conf.d/


