# Generated by Django 2.2.2 on 2019-11-24 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('url', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='分享链接')),
                ('pwd', models.CharField(max_length=4, null=True, verbose_name='提取码')),
                ('expiration', models.DateTimeField(verbose_name='过期时间点')),
                ('my_catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Catalogue')),
            ],
            options={
                'verbose_name': '分享',
                'verbose_name_plural': '分享',
            },
        ),
    ]
