# Generated by Django 2.2.2 on 2019-11-26 04:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20191125_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改日期'),
        ),
    ]
