# Generated by Django 2.2.2 on 2019-11-24 09:02

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('max_size', models.BigIntegerField(default=5368709120, verbose_name='最大容量')),
                ('used_size', models.BigIntegerField(default=0, verbose_name='已用容量')),
                ('token', models.CharField(max_length=64, null=True, verbose_name='user token')),
                ('storage', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='my_master', to='storage.Catalogue')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
