# Generated by Django 2.2.2 on 2019-11-24 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='群组名')),
            ],
            options={
                'verbose_name': '群组',
                'verbose_name_plural': '群组',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('master', '创建人'), ('manager', '管理员'), ('member', '成员')], max_length=7, verbose_name='权限')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.Group')),
            ],
            options={
                'verbose_name': '组员',
                'verbose_name_plural': '组员',
            },
        ),
    ]
