name: test and build

on:
    push:
        branches: master

jobs:
    test_backend:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-python@v1
              with:
                python-version: 3.8
            - name: install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r backend/requirements.txt
            - name: lint
              run: |
                pip install flake8
                cd backend
                flake8 . --statistics --exclude .env,migrations --max-line-length 127
            - name: test
              run: |
                cd backend
                python manage.py makemigrations user group storage share
                pytest
