name: test and build

on:
    push:
        branches: master

jobs:
    test_backend:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-python@v1
              with:
                python-version: 3.8
            - run: |
                python -m pip install --upgrade pip
                pip install -r backend/requirements.txt
            - run: |
                pip install flake8
                cd backend
                flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            - run: cd backend && pytest
